Sprint 05
Rozetka220/MovieQuiz-ios pull request #3
Opened 2023-01-10 19:17 UTC by Rozetka220

Это было очень и очень сложно.  Особенно делегаты.

2023-01-11 20:33 UTC, helecta requested changes

2023-01-11 20:33 UTC, helecta commented on MovieQuiz/Models/QuizResultsViewModel.swift
> +// для состояния "Результат квиза"
Здорово, что добавляешь комментарии. Если добавлять через /// , а не // , то тогда можно будет быстро прочитать документацию, если зажать кнопку option и навести на класс.

2023-01-11 20:33 UTC, helecta commented on MovieQuiz/Presentation/AlertPresenter.swift
> +    internal weak var delegateAlert = UIViewController()
Для того чтобы показать алерт, не нужно специально создавать новый ViewController. Достаточно передавать контроллер, на котором необходимо показать алерт, сюда как делегат. Закомментированный init это верный ход рассуждений

2023-01-11 20:33 UTC, helecta commented on MovieQuiz/Services/AlertPresenterProtocol.swift
> +    var delegateAlert: UIViewController? {get set}
Название delegateAlert не удачное, обычно слово delegate должно быть в конце.

2023-01-11 20:33 UTC, helecta commented on MovieQuiz/Services/QuestionFactoryProtocol.swift
> +protocol QuestionFactoryProtocol : QuestionFactoryDelegate {
Почему он QuestionFactoryDelegate?

2023-01-11 20:33 UTC, helecta commented on MovieQuiz/Services/QuestionFactoryDelegate.swift
> +    var delegate: QuestionFactoryDelegate? { get set }
Тут не нужен этот delegate. 
У самой фабрики есть делегат ` weak var delegate: QuestionFactoryDelegate?`, который занимается обработкой момента получения следующего вопроса( в нашем случае делегатом будет viewController, который и займется обработкой этого момента)

2023-01-11 20:33 UTC, helecta commented on MovieQuiz/Services/StatisticService.swift
> +    var getSetTotalAccuracy: Double {
Свойства не принято так называть, ошибка что тут есть глаголы getSet. 
Аналогично нужно исправить и все остальные свойства

2023-01-11 20:33 UTC, helecta commented on MovieQuiz/Services/StatisticService.swift
> +                  let totalAccuracy = try? JSONDecoder().decode(Double.self, from: data) else {
Тут можно упростить, обрати внимание UserDefaults поддерживает работу с примитивными типами [для чтения](https://developer.apple.com/documentation/foundation/userdefaults/1407405-integer) и [записи](https://developer.apple.com/documentation/foundation/userdefaults/1413614-set).

2023-01-11 20:33 UTC, helecta commented on MovieQuiz/Services/StatisticService.swift
> +        //refresh()
Перед сдачей стоит убирать весь закомментированный код.

2023-01-11 20:33 UTC, helecta commented on MovieQuiz/Services/StatisticService.swift
> +    func refresh(){
Этот метод нигде не используется(кроме как в закомментированном коде), поэтому его стоит удалить

2023-01-11 20:33 UTC, helecta commented on MovieQuiz/Presentation/MovieQuizViewController.swift
> +            let text = "Ваш результат: \(correctAnswers) из \(questionsAmount)\nКоличество сыгранных квизов: \(serviceStatictic.gamesCount)\nРекорд: \(serviceStatictic.bestGame.correct)/\(questionsAm
Можно использовать [многострочный вариант строки](https://www.swiftbysundell.com/tips/multiline-string-literal-tips-and-tricks/), чтобы строчка кода умещалась в столбец

2023-01-11 20:33 UTC, helecta commented on MovieQuiz/Presentation/MovieQuizViewController.swift
> +            let text = "Ваш результат: \(correctAnswers) из \(questionsAmount)\nКоличество сыгранных квизов: \(serviceStatictic.gamesCount)\nРекорд: \(serviceStatictic.bestGame.correct)/\(questionsAm
Обрати внимание на макет. Там в тексте "Ваш результат" дальше нет "из", используется формат "n/10"

2023-01-11 20:33 UTC, helecta commented on MovieQuiz/Services/AlertPresenterProtocol.swift
> +    func requestGameOverBtn(model: AlertModel)
Не удачное название метода. 
Для того чтобы понять, как лучше называть методы, можно задать вопрос, что делает AlertPresenter, за что отвечает этот класс?
В нашем случае его ответственность - это показывает алерт, поэтому и метод стоит назвать так.

2023-01-11 20:33 UTC, helecta commented on MovieQuiz/Presentation/MovieQuizViewController.swift
> +    func requestGameOverBtn(model: AlertModel){}
Методы стоит перенести к методам, даже если они пустые

2023-01-11 20:33 UTC, helecta commented on MovieQuiz/Presentation/MovieQuizViewController.swift
> +    @IBAction func yesButton(_ sender: Any) {
Это метод, поэтому в название стоит использовать глагол, например Pressed

2023-01-11 20:33 UTC, helecta commented on MovieQuiz/Presentation/MovieQuizViewController.swift
> +    @IBAction func noButton(_ sender: Any) {
Аналогично

2023-01-11 21:11 UTC, Rozetka220 commented on MovieQuiz/Models/QuizResultsViewModel.swift
> +// для состояния "Результат квиза"
Даже и подумать не мог, хотя замечал, что комментарий с "///" тоже существует. Спасибо!

2023-01-11 21:26 UTC, Rozetka220 commented on MovieQuiz/Presentation/MovieQuizViewController.swift
> +    func requestGameOverBtn(model: AlertModel){}
И вправду, это результат борьбы, когда xcode принимал соответствие протоколу только через Fix, я потом побоялся что-то трогать

2023-01-11 21:39 UTC, Rozetka220 commented on MovieQuiz/Presentation/MovieQuizViewController.swift
> +            let text = "Ваш результат: \(correctAnswers) из \(questionsAmount)\nКоличество сыгранных квизов: \(serviceStatictic.gamesCount)\nРекорд: \(serviceStatictic.bestGame.correct)/\(questionsAm
Не совсем понял смысл. Он в том, что в коде все выглядело более опрятно и читаемо?
<img width="934" alt="изображение" src="https://user-images.githubusercontent.com/16082900/211923502-4d94afb0-7232-4f0f-acc6-1f2937944e06.png">

2023-01-11 21:57 UTC, Rozetka220 commented on MovieQuiz/Services/StatisticService.swift
> +    var getSetTotalAccuracy: Double {
Могу ли я сделать просто вот так? 
<img width="617" alt="изображение" src="https://user-images.githubusercontent.com/16082900/211926502-c466cea3-fd7f-4387-8cb8-ca5d0f0e3760.png">

2023-01-11 22:05 UTC, Rozetka220 commented on MovieQuiz/Services/QuestionFactoryProtocol.swift
> +protocol QuestionFactoryProtocol : QuestionFactoryDelegate {
<img width="1294" alt="изображение" src="https://user-images.githubusercontent.com/16082900/211927714-bf83eb0f-6a48-4571-b480-2f72df86ab29.png">
Видимо для этого, я уже не помню, зачем так было нужно. На сколько критично, если я это оставлю как есть?

2023-01-12 06:47 UTC, helecta commented on MovieQuiz/Services/QuestionFactoryProtocol.swift
> +protocol QuestionFactoryProtocol : QuestionFactoryDelegate {
Это довольно важный момент. Вопрос был скорее наводящим) 
Попробуй разобраться, какая ответственность должна быть у QuestionFactoryProtocol и какая у QuestionFactoryDelegate.
Если возникнут сложности, пиши либо тут либо Наставнику.
P.S следующий комментарий к QuestionFactoryDelegate.swift в общем-то должен немного помочь

2023-01-12 06:48 UTC, helecta commented on MovieQuiz/Services/StatisticService.swift
> +    var getSetTotalAccuracy: Double {
Да, так и нужно

2023-01-12 06:50 UTC, helecta commented on MovieQuiz/Presentation/MovieQuizViewController.swift
> +            let text = "Ваш результат: \(correctAnswers) из \(questionsAmount)\nКоличество сыгранных квизов: \(serviceStatictic.gamesCount)\nРекорд: \(serviceStatictic.bestGame.correct)/\(questionsAm
Да, все верно. Так просто лучше читаемость кода

2023-01-12 06:52 UTC, Rozetka220 commented on MovieQuiz/Services/QuestionFactoryProtocol.swift
> +protocol QuestionFactoryProtocol : QuestionFactoryDelegate {
Хорошо, попробую сегодня разобраться. Моя вчерашняя попытка завершилась крахом с кучей ошибок.  Перечитав с утра так и подумал, что ключом к разгадке может быть следующий комментарий. Спасибо!

2023-01-12 15:48 UTC, Rozetka220 commented on MovieQuiz/Services/QuestionFactoryProtocol.swift
> +protocol QuestionFactoryProtocol : QuestionFactoryDelegate {
Я думаю, ответственность такая: 
QuestionFactoryProtocol - нужен, что бы получать вопросы из массива вопросов (хранилища вопросов)

QuestionFactoryDelegate - нужен, что бы этот вопрос можно было передать в viewController

viewController - отображает вопрос на экране

2023-01-12 16:13 UTC, Rozetka220 commented on MovieQuiz/Services/QuestionFactoryProtocol.swift
> +protocol QuestionFactoryProtocol : QuestionFactoryDelegate {
Никак не могу понять, как про инициализировать _weak var delegate: QuestionFactoryDelegate?_

В учебнике написано, что инициализация происходит через свойство, однако это больше похоже на первый вариант из тема "**Делегаты**" (второй скриншот)
<img width="963" alt="изображение" src="https://user-images.githubusercontent.com/16082900/212118630-c3001733-9dd2-4324-9067-c007d321764a.png">

<img width="1440" alt="изображение" src="https://user-images.githubusercontent.com/16082900/212119193-4fa1f6d0-1a99-4afd-be2f-dbb2da7ff93b.png">


В итоге у меня выходит ошибка "_Argument passed to call that takes no arguments_", что кажется логичным, ведь конструктора на свойство _delegate_ у меня нет

<img width="989" alt="изображение" src="https://user-images.githubusercontent.com/16082900/212120942-f9332192-5f22-4394-91b9-318268b8bbd3.png">

 
Если я попробую про инициализировать через свойство так, как я понима, то у меня выходит ошибка "_Value of type 'any QuestionFactoryProtocol' has no member 'delegate'_" И ведь правда, переменная делегата в _MovieQuizViewController_ типа _QuestionProtocol_, а в нем у меня нет такого свойства

<img width="961" alt="изображение" src="https://user-images.githubusercontent.com/16082900/212120615-9f3ffaba-d173-4894-9792-6476ede82818.png">

2023-01-12 16:20 UTC, Rozetka220 commented on MovieQuiz/Services/QuestionFactoryProtocol.swift
> +protocol QuestionFactoryProtocol : QuestionFactoryDelegate {
В итоге выбрал инициализацию через инициализацию и добавил конструктор в _QuestionFactory_, но я не помню, что бы в учебнике это было и не отхожу ли я так от рамок, в которых я должен справиться с задачей?
Говорю, что не помню, потому что уже нет сил перечитывать этот спринт и меня от него тошнит, и проверять, действительно ли там не было конструктора или просто я где-то проглядел и накосячил. Это не правильно, но я ничего не могу с собой поделать
<img width="650" alt="изображение" src="https://user-images.githubusercontent.com/16082900/212121892-233f5e2a-3fd3-4954-9495-0e70814ce2a4.png">

2023-01-12 16:26 UTC, Rozetka220 commented on MovieQuiz/Services/QuestionFactoryProtocol.swift
> +protocol QuestionFactoryProtocol : QuestionFactoryDelegate {
В общем, буду ждать тут от тебя ответа, все остальное исправил, по крайней мере мне так кажется. Если все верно, сразу скину проект на перепроверку. Надеюсь, завтра вечером или хотя бы ночью, я уже смогу приступить к новому спринту.

2023-01-12 17:35 UTC, Rozetka220 commented on MovieQuiz/Services/QuestionFactoryProtocol.swift
> +protocol QuestionFactoryProtocol : QuestionFactoryDelegate {
Отправил, если надо будет что-то исправить, исправлю и перезалью

2023-01-12 19:41 UTC, helecta commented on MovieQuiz/Services/QuestionFactoryProtocol.swift
> +protocol QuestionFactoryProtocol : QuestionFactoryDelegate {
Да, действительно в учебнике не совсем ясно сказано. 
Как я поняла, здесь:
> Мы реализовали инъекцию через свойство. Поэтому задавать делегата мы будет во viewDidLoad методе.

речь была об инъекции через свойство questionFactory для MovieQuizViewController.
Т.е инъекции через свойство происходит во viewDidLoad:
`questionFactory = QuestionFactory(delegate: self)`,
а если бы была инъекции через инициализацию, то она выглядела бы так:
`private var questionFactory: QuestionFactoryProtocol? =  QuestionFactory(delegate: self)`

Сейчас ты сделал все как надо

2023-01-12 19:54 UTC, helecta commented on MovieQuiz/Presentation/AlertPresenter.swift
> +    func viewGameOverAlert(model: AlertModel) {
Лучше назвать не `viewGameOverAlert`, а `presentGameOverAlert`.
View в название может ввести в заблуждение, что это UIView.
Present - обычно означает показать поверх текущего View
Show - вместо текущего View

2023-01-12 19:54 UTC, helecta commented on MovieQuiz/Presentation/MovieQuizViewController.swift
>  final class MovieQuizViewController: UIViewController, QuestionFactoryDelegate, AlertPresenterProtocol {
Возможно забыл убрать, зачем MovieQuizViewController отвечает протоколу AlertPresenterProtocol?
Если убрать, то не забудь убрать и
`var alertDelegate: UIViewController?`
`func viewGameOverAlert(model: AlertModel){}`

2023-01-12 20:00 UTC, Rozetka220 commented on MovieQuiz/Presentation/AlertPresenter.swift
> +    func viewGameOverAlert(model: AlertModel) {
Понял, принял, спасибо!

2023-01-12 20:01 UTC, Rozetka220 commented on MovieQuiz/Presentation/MovieQuizViewController.swift
>  final class MovieQuizViewController: UIViewController, QuestionFactoryDelegate, AlertPresenterProtocol {
Возможно. Очень сильно мучился с эти заданием.

2023-01-15 16:01 UTC, merged