Sprint 07
Rozetka220/MovieQuiz-ios pull request #5
Opened 2023-01-16 21:16 UTC by Rozetka220

2023-01-17 23:24 UTC, mmbabaev requested changes

2023-01-17 23:24 UTC, mmbabaev commented on MovieQuiz/Presentation/MovieQuizPresenter.swift
> +    func buttonDisable(isDisable: Bool)
неудачное название, без глагола. setButtonEnabled(_ isEnabled: Bool)

2023-01-17 23:24 UTC, mmbabaev commented on MovieQuiz/Presentation/MovieQuizPresenter.swift
> +    private let statisticService: StatisticService!
тут можно оставить неопциональный тип

2023-01-17 23:24 UTC, mmbabaev commented on MovieQuiz/Presentation/MovieQuizPresenter.swift
> +    private let statisticService: StatisticService!
StatisticService! -> StatisticService

2023-01-17 23:24 UTC, mmbabaev commented on MovieQuiz/Presentation/MovieQuizPresenter.swift
> +        //на сколько необходимо создавать отельную переменную givenAnswer? Я как понимаю это просто для читаемости кода
на самом деле вы правы, не нужно. Я бы так не делал. Если хотим внутри видеть эту переменную под другим именем, можно так: 
`private func didAnswer(isYes givenAnswer: Bool) {`

2023-01-17 23:24 UTC, mmbabaev commented on MovieQuiz/Presentation/MovieQuizPresenter.swift
> +        //tututut
не надо так

2023-01-17 23:24 UTC, mmbabaev commented on MovieQuiz/Presentation/MovieQuizPresenter.swift
> +        currentQuestion.correctAnswer == givenAnswer ? showAnswerResult(isCorrect: true) : showAnswerResult(isCorrect: false)
showAnswerResult(isCorrect: isYes)

2023-01-17 23:24 UTC, mmbabaev commented on MovieQuiz/Presentation/MovieQuizViewController.swift
> +    //private var questionFactory: QuestionFactoryProtocol?
не нужно оставлять никакой закомментированный код в работе здесь и ниже

2023-01-17 23:24 UTC, mmbabaev commented on MovieQuiz/Presentation/MovieQuizPresenter.swift
> +        statisticService.store(correct: correctAnswers, total: questionsAmount)
вы наделяете функцию сайд эффектом, который не заложен в названии. Тот, кто вызывает функцию (клиент кода), не может знать, что эта  функция помимо составления message еще сохраняет какие-то данные. 

Нужно убрать отсюда эту строчку

2023-01-17 23:24 UTC, mmbabaev commented on MovieQuiz/Presentation/MovieQuizPresenter.swift
> +    // Я вроде как вполне себе могй спокойно обойтись без этого метода, не совсем понимаю, зачем его использовать?
большие функции, классы принято декомпозировать на маленькие. Эта функция может отвечать только за составление сообщения

2023-01-17 23:24 UTC, mmbabaev commented on MovieQuiz/Presentation/MovieQuizPresenter.swift
> +            viewController?.show(quiz: viewModel)
получилось очень сложно и много лишней работы. Эта функция вызывается, но ее viewModel не нужна для показа и не используется для показа

2023-01-17 23:24 UTC, mmbabaev commented on MovieQuiz/Presentation/MovieQuizPresenter.swift
> +    init(viewController: MovieQuizViewControllerProtocol) {
обычно принято писать init после объявления свойств

2023-01-17 23:24 UTC, mmbabaev commented on MovieQuiz/Presentation/MovieQuizViewController.swift
> +final class MovieQuizViewController: UIViewController, AlertPresenterProtocol, MovieQuizViewControllerProtocol {
это мелочь, но часто принято  выделять реализации протокола в отдельный экстеншен:

```
extension MovieQuizViewController: AlertPresenterProtocol { 
 // методы протокола
}
```

2023-01-17 23:24 UTC, mmbabaev commented on MovieQuiz/Presentation/MovieQuizViewController.swift
>      var alertDelegate: UIViewController?
это не нужно

2023-01-17 23:24 UTC, mmbabaev commented on MovieQuiz/Presentation/MovieQuizViewController.swift
> +            message:  presenter.makeResultMessage(), // result.text,
вот тут непонятно. Передали в функцию result, что-то из него используем, что-то нет. Можно либо создавать полностью AlertModel в основном Presenter, либо `message` заполнять в `QuizResultsViewModel`

2023-01-17 23:24 UTC, mmbabaev commented on MovieQuiz/Presentation/MovieQuizViewController.swift
> +            nButton.isEnabled=true
не экономьте на названиях переменных, классов, функций, это плохая практика. `yesButton`, `noButton`

2023-01-17 23:24 UTC, mmbabaev commented on MovieQuizTests/MovieQuizTests.swift
> +        let result = arithmeticsOperation.additional(num1: num1, num2: num2){result in
1) объект теста не используется в программе
2) `let result` не используется в тесте

2023-01-17 23:24 UTC, mmbabaev commented on MovieQuizUITests/MovieQuizUITests.swift
> +        let firstPosterData = firstPoster.screenshot().pngRepresentation
о, здорово, что сразу сделали через pngRepresentation

2023-01-17 23:24 UTC, mmbabaev commented on MovieQuizUITests/MovieQuizUITests.swift
> +    func testLaunchPerformance() throws {
удалить

2023-01-17 23:24 UTC, mmbabaev commented on MovieQuizTests/MoviesLoaderTests.swift
> +                XCTAssertEqual(movies.items.count, 2)
в идеале можно проверить и контент movies.items (свойства item)

2023-01-17 23:24 UTC, mmbabaev commented on MovieQuizTests/MoviesLoaderTests.swift
> +            case .success(let movies):
объявление movies не нужно. Обращайте внимание на ворнинги. Хорошая практика относиться к ним как к ошибкам

2023-01-17 23:24 UTC, mmbabaev commented
<img width="534" alt="Screen Shot 2023-01-18 at 02 05 39" src="https://user-images.githubusercontent.com/12600807/213034142-47f9b358-58de-4180-b5de-094e4b08740a.png">
На первом запуске

2023-01-18 02:59 UTC, Rozetka220 commented on MovieQuizTests/MoviesLoaderTests.swift
> +            case .success(let movies):
> объявление movies не нужно. Обращайте внимание на ворнинги. Хорошая практика относиться к ним как к ошибкам



> <img alt="Screen Shot 2023-01-18 at 02 05 39" width="534" src="https://user-images.githubusercontent.com/12600807/213034142-47f9b358-58de-4180-b5de-094e4b08740a.png">
> На первом запуске

Странно, сейчас занулил все результаты используя функцию refresh() и запустил заново, у меня как будто бы все нормально. Что я делаю не так?     
```
func store(correct count: Int, total amount: Int) {
        refresh()
        var newBestGame = GameRecord(correct: count, total: amount, date: Date())
        gamesCount += 1
        if newBestGame > bestGame {
            bestGame = newBestGame
        }
        totalAccuracy+=Double(count)
        averageAccuracy(correct: count, total: amount)
    }

func refresh(){
        userDefaults.set(0, forKey: Keys.total.rawValue)

        userDefaults.set(0, forKey: Keys.gamesCount.rawValue)

        userDefaults.set(0, forKey: Keys.bestGame.rawValue)
    } 
```
<img width="365" alt="изображение" src="https://user-images.githubusercontent.com/16082900/213071753-5c90077a-96b4-4775-a114-6e1d10f7411c.png">

2023-01-18 20:43 UTC, Rozetka220 commented
Ладно, не дождался ответов. Я сдаюсь, все равно уже дедлайн, смысла тянуть нет. Дропаю на проверку то, что есть

2023-01-19 18:51 UTC, mmbabaev approved these changes

2023-01-19 18:51 UTC, mmbabaev commented on MovieQuiz/Presentation/MovieQuizPresenter.swift
> +    func yesBtnPressed() {
в swift (и objc до него)  не принято особо сокращать переменные, функции таким образом

2023-01-19 18:51 UTC, mmbabaev commented on MovieQuiz/Presentation/MovieQuizPresenter.swift
> +    func yesBtnPressed() {
Btn имею в виду

2023-01-19 18:51 UTC, mmbabaev commented on MovieQuiz/Presentation/MovieQuizPresenter.swift
> +                message:  makeResultMessage(), // result.text,
удалить коммент

2023-01-19 18:51 UTC, mmbabaev commented on MovieQuiz/Presentation/MovieQuizViewController.swift
> +    @IBOutlet weak private var activityIndicator: UIActivityIndicatorView!
принято` private weak var`

2023-01-19 18:51 UTC, mmbabaev commented on MovieQuiz/Presentation/MovieQuizViewController.swift
> +        if isCorrectAnswer == true {
`if isCorrectAnswer {`

2023-01-19 18:51 UTC, mmbabaev commented on MovieQuiz/Presentation/MovieQuizViewController.swift
> +            presenter.didAnswer(isCorrectAnswer: isCorrectAnswer) //tut
tut

2023-01-19 18:51 UTC, mmbabaev commented on MovieQuiz/Presentation/MovieQuizViewController.swift
> +            yButton.isEnabled=false
noButton, yesButton. 
также можно: 
```
yesButton.isEnabled = !isDisabled
noButton.isEnabeld = !isDIsabled
```

2023-01-19 18:51 UTC, mmbabaev commented on MovieQuiz/Services/NetworkClient.swift
> +struct NetworkClient: NetworkRouting {
Лучше не задавать вопросы в комментах к работе на проверку, задавайте их наставнику. 

Мое мнение - тут не особо важно, можно и класс использовать. Иногда руководствуются правилом в первую очередь использовать `struct`, если не требуется что-то от `class` (reference семантика, наследование и тд)

2023-01-19 18:51 UTC, mmbabaev commented on MovieQuiz/Services/NetworkClient.swift
> +struct NetworkClient: NetworkRouting {
можно найти различные статьи по запросу `struct vs class`

2023-01-19 18:54 UTC, mmbabaev approved these changes

2023-01-20 01:59 UTC, merged